### ISSUE TITLE
Browser search doesn't bring up the virtual keyboard, thus making search impossible.

### ISSUE THREAD

**Issue by MagmaBro123** [jessebofill/DeckWebBrowser#10]
Title.

**Comment by jessebofill** [comment]
Are you on steam client beta or stable? and can you bring up the keyboard manually using the hotkey?

**Comment by MagmaBro123** [comment]
Stable. Steam + X doesn't bring it up either.

**Comment by MagmaBro123** [comment]
Nothing. No keyboard pops up.

**Comment by jessebofill** [comment]
There’s not much information to go on here. Can you give me more specifics / what happens step by step? Maybe a screenshot? Can you navigate to the search bar with the controls? What version of the plugin do you have?

**Comment by jessebofill** [comment]
> > There’s not much information to go on here. Can you give me more specifics / what happens step by step? Maybe a screenshot? Can you navigate to the search bar with the controls? What version of the plugin do you have?
> 
> Tapping on the Search doesn't bring up the keyboard. I can go to it via controls as well, but again, that doesn't bring up the keyboard. I'm using the latest version the Store gives me.

Are you pressing “A” button when you navigate to it?

**Comment by Luther120** [comment]
hey i'm kind of having the same issue, i think. (apologizes if i word this badly i should have gone to bed hours ago as of writing this lol.)

i'm currently using v2.10.14 of Decky, v1.3.0-1 of DeckWebBrowser, and v1.0.0-1 of Bookmarks (by Blake Leonard, i unfortunately cant seem to find a github page for it. god i wish github links were listed somewhere with Decky.)

i'm currently trying to test out if i can tweet from my steam deck, but on the top next to where it has the url it says "touch only" and the same thing is happening where i can't bring up the keyboard at all. Steam + X doesnt bring the keyboard up, Select doesn't, and i could have sworn there was a button to bring it up when you press the button with the 3 dots but that doesnt even appear either. (not sure how much bookmarks is affecting this, because i am trying to use it from a saved bookmark but when i tried doing this from DeckWebBrowser the same thing was happening. just thought i'd list it for clarity's sake.)

so really the only issue for _me_ is that it's forcing me to use touch, so that's probably preventing me from opening the keyboard. i just figured this was the right thread to say this, so sorry if this isnt relevant or anything. im not very much of a coder and dont use github to interact with people at all so feel free to move this to another thread or something. it just seems like this might be the issue OP is having, so i figured i'd try to possibly solve both our issues at once, lol.

**Comment by jessebofill** [comment]
> hey i'm kind of having the same issue, i think. (apologizes if i word this badly i should have gone to bed hours ago as of writing this lol.)
> 
> i'm currently using v2.10.14 of Decky, v1.3.0-1 of DeckWebBrowser, and v1.0.0-1 of Bookmarks (by Blake Leonard, i unfortunately cant seem to find a github page for it. god i wish github links were listed somewhere with Decky.)
> 
> i'm currently trying to test out if i can tweet from my steam deck, but on the top next to where it has the url it says "touch only" and the same thing is happening where i can't bring up the keyboard at all. Steam + X doesnt bring the keyboard up, Select doesn't, and i could have sworn there was a button to bring it up when you press the button with the 3 dots but that doesnt even appear either. (not sure how much bookmarks is affecting this, because i am trying to use it from a saved bookmark but when i tried doing this from DeckWebBrowser the same thing was happening. just thought i'd list it for clarity's sake.)
> 
> so really the only issue for _me_ is that it's forcing me to use touch, so that's probably preventing me from opening the keyboard. i just figured this was the right thread to say this, so sorry if this isnt relevant or anything. im not very much of a coder and dont use github to interact with people at all so feel free to move this to another thread or something. it just seems like this might be the issue OP is having, so i figured i'd try to possibly solve both our issues at once, lol.

The things is Bookmarks works completely separately and differently from Web Browser. Perhaps you are having the same issue as op but I need more information specific to what’s happening with Web Browser.

**Comment by jessebofill** [comment]
Web browser patches the built in search bar (that normally searches for games in steam store or user library) and changes it to search via a search engine or navigate to a site. This is the only plugin that modifies the behavior of the search bar, and for good reason because it is problematic and difficult to get to do what you want. With all that said in short the typing in the search bar with touch screen or touching the bar with the touch screen basically doesn’t work. The way it is meant to work is by navigating to the search bar with the dpad controls, or alternatively pressing the select button upon either of which the current url should be selected (highlight in blue), at which point you have to press “A” to “click” the text box which should then pop up the key board (then typing must be done with touch pad). If these steps are followed and the keyboard still doesn’t show, please let me know. If these steps are followed and at any step doesn’t produce the specific behavior specified then please let me know. I need to be as specific as possible in order to diagnose whatever problems there could be.

**Comment by MagmaBro123** [comment]
> > > There’s not much information to go on here. Can you give me more specifics / what happens step by step? Maybe a screenshot? Can you navigate to the search bar with the controls? What version of the plugin do you have?
> > 
> > 
> > Tapping on the Search doesn't bring up the keyboard. I can go to it via controls as well, but again, that doesn't bring up the keyboard. I'm using the latest version the Store gives me.
> 
> Are you pressing “A” button when you navigate to it?

Yes.

**Comment by jessebofill** [comment]
> > > > There’s not much information to go on here. Can you give me more specifics / what happens step by step? Maybe a screenshot? Can you navigate to the search bar with the controls? What version of the plugin do you have?
> > > 
> > > 
> > > Tapping on the Search doesn't bring up the keyboard. I can go to it via controls as well, but again, that doesn't bring up the keyboard. I'm using the latest version the Store gives me.
> > 
> > 
> > Are you pressing “A” button when you navigate to it?
> 
> Yes.

Does it highlight the text in blue? Can you take a short video of you trying it?

**Comment by MagmaBro123** [comment]
> > > > > There’s not much information to go on here. Can you give me more specifics / what happens step by step? Maybe a screenshot? Can you navigate to the search bar with the controls? What version of the plugin do you have?
> > > > 
> > > > 
> > > > Tapping on the Search doesn't bring up the keyboard. I can go to it via controls as well, but again, that doesn't bring up the keyboard. I'm using the latest version the Store gives me.
> > > 
> > > 
> > > Are you pressing “A” button when you navigate to it?
> > 
> > 
> > Yes.
> 
> Does it highlight the text in blue? Can you take a short video of you trying it?

No clue how to take screenshots or videos via Deck. Though manually doing the controller way of getting to Search seems to work.

**Comment by jessebofill** [comment]
> No clue how to take screenshots or videos via Deck. Though manually doing the controller way of getting to Search seems to work.

ok. Closing this issue then.

**Comment by Dav1d-Fn** [comment]
I have the same issue, I can't open the virtual keyboard on the web browser at all. In my library it appears normally. I'm on the newest stable version of steam os and newest version of your plugin. I'm using the OLED model.

Are there any updates?

**Comment by 2315506431** [comment]
> I have the same issue, I can't open the virtual keyboard on the web browser at all. In my library it appears normally. I'm on the newest stable version of steam os and newest version of your plugin. I'm using the OLED model.
> 
> Are there any updates?

I accidentally found that turning off the Transparent Keyboard (I've also found that "Smaller Keyboard" also causes this issue.) in the CSS Loader plugin resolved the issue. If you have the same plugin installed, it might be helpful for you too.

**Comment by polocatfan** [comment]
> > I have the same issue, I can't open the virtual keyboard on the web browser at all. In my library it appears normally. I'm on the newest stable version of steam os and newest version of your plugin. I'm using the OLED model.
> > Are there any updates?
> 
> I accidentally found that turning off the Transparent Keyboard (I've also found that "Smaller Keyboard" also causes this issue.) in the CSS Loader plugin resolved the issue. If you have the same plugin installed, it might be helpful for you too.

didn't help
EDIT: It's inconsistently working. Sometimes it'll bring up the keyboard fine, other times it won't.
