### ISSUE TITLE
Back / Forward bindings and scrolling with xbox controller

### ISSUE THREAD

**Issue by BohanJones** [jessebofill/DeckWebBrowser#11]
Firstly thank you so much for making this, its so handy for looking up wikis/guides midgame.

My issues are that I wish I could rebind the back/foward commands to regular controller buttons (xbox gamepad in my case) or at least have a way to go back/fwd in the GUI - as sometimes i click on a link and have no way to go back a page.

I also wish i could move the mouse via the steam deck instead of only touchscreen.

Its also not possible to scroll on an xbox controller - could this be bound to left stick / dpad?

Thanks so much! Typed all this on my SD with your plugin :)

**Comment by jessebofill** [comment]
Maybe I’ll bind back and forward to L2/R2. I originally left those unbound because I wanted to try to get touch pad mouse working without having to hold steam button and use those for clicks, but it ended up not working out. As for the mouse you actually can use the system mouse by just holding the steam button and using the trackpad. That’s a system wide thing. That actually should work on Xbox controller too by using Xbox button and right stick, at least it does with switch pro controller. As for scrolling with controller that should also just work the same way as it does on deck. Sometimes the page does not take focus correctly and doesn’t scroll. If this happens just press b to send focus back to the tab bar and then press down again to focus the page.

the latest steam update also broke some stuff I gotta fix, but I haven’t  had a chance to to look into it. I’m busy with some stuff currently so when I get a chance to work on the plugin I’ll try to take care of all this stuff.

**Comment by BohanJones** [comment]
Thanks so much man, you're a legend. Truly no rush. Thanks for replying. I'll try fiddling around to get the xbox controller to work/scrolls. 

Thanks again!

**Comment by jessebofill** [comment]
No problem. Yeah it might be a while but I’ll post back here when I get to it.

**Comment by jessebofill** [comment]
Ok. Update is coming soon. Just has to go through decky testing. Page back/forward are now also bound to L2/R2.
